name: Deploy Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub Environment to deploy"
        required: true
        type: environment

  workflow_call:
    inputs:
      environment:
        description: "GitHub Environment to deploy"
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    name: Deploy Frontend to ${{ inputs.environment }}
    needs: test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
      VITE_API_URL: ${{ vars.RELATIVE_API_URL }}
      # COGNITO
      VITE_COGNITO_USER_POOL_ID: ${{ vars.COGNITO_USER_POOL_ID }}
      VITE_COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}
      VITE_COGNITO_LOGIN_URL: ${{ vars.COGNITO_LOGIN_URL }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Install Dependencies
        run: npm ci --prefer-offline

      - name: Build Project
        run: npm run build

      - name: Upload Dist Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.environment }}-dist-artifacts
          path: ./dist/
          retention-days: 7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: frontend-${{ inputs.environment }}-deploy

      - name: Deploy to S3
        run: aws s3 sync ./dist "s3://${S3_BUCKET}" --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" \
            --paths "/*"
